name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: forms-editor-poc
          directory: build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
        env:
          DEBUG: '*'
      - name: Log Deployment Error
        if: failure()
        run: |
          echo "Cloudflare Pages deployment failed"
          echo "API Token (length): ${#CLOUDFLARE_API_TOKEN}"
          echo "Account ID (length): ${#CLOUDFLARE_ACCOUNT_ID}"
          echo "Project Name: ${{ github.event.repository.name }}"
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}