name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: forms-editor-poc
          directory: build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify Deployment
        run: |
          echo "Waiting for deployment to propagate..."
          sleep 60  # Wait for 60 seconds
          DEPLOY_URL=$(curl -s "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/pages/projects/forms-editor-poc" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" | jq -r '.result.domains[0]')
          HTTP_STATUS=$(curl -o /dev/null -s -w "%{http_code}" $DEPLOY_URL)
          if [ $HTTP_STATUS -eq 200 ]; then
            echo "Deployment successful! Site is accessible at $DEPLOY_URL"
          else
            echo "Deployment may have failed. HTTP status: $HTTP_STATUS"
            exit 1
          fi